language: python
python:
  - "2.6"
  - "2.7"
install:
  - travis_retry pip install -r test/requirements.txt
  - travis_retry pip install coveralls
  - travis_retry pip install -e .
script: py.test --cov=mygrate
after_success:
  - coveralls
